see if this pushes data

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -235,11 +235,14 @@ jobs:
           fi
           if [[ $num_fails != 0 ]]; then
             echo -e "$num_fails test(s) failed:\n${failed_tests}"
+            exit $num_fails
+          else
+            echo -e "No issues detected in this build".
+            exit $num_fails
           fi
-          exit $num_fails
       - name: "Send Message"
         uses: ./.github/actions/slack-file
-        if: ${{ failure() }}
+        #if: ${{ failure() }}
         with:
           payload-file: ${{ env.MESSAGE_PAYLOAD_FILE }}
           webhook: ${{ secrets.WEBHOOK_FLAKY_TESTS }}
